const SIDEBAR_OPEN = "SIDEBAR_OPEN";
const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";
const LOAD_PRODUCTS = "LOAD_PRODUCTS";
const SET_GRIDVIEW = "SET_GRIDVIEW";
const SET_LISTVIEW = "SET_LISTVIEW";
const UPDATE_SORT = "UPDATE_SORT";
const SORT_PRODUCTS = "SORT_PRODUCTS";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
const CLEAR_CART = "CLEAR_CART";
const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";

export {
  SIDEBAR_OPEN,
  SIDEBAR_CLOSE,
  GET_PRODUCTS_BEGIN,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_ERROR,
  GET_SINGLE_PRODUCT_BEGIN,
  GET_SINGLE_PRODUCT_SUCCESS,
  GET_SINGLE_PRODUCT_ERROR,
  LOAD_PRODUCTS,
  SET_GRIDVIEW,
  SET_LISTVIEW,
  UPDATE_SORT,
  SORT_PRODUCTS,
  UPDATE_FILTERS,
  FILTER_PRODUCTS,
  CLEAR_FILTERS,
  ADD_TO_CART,
  REMOVE_CART_ITEM,
  TOGGLE_CART_ITEM_AMOUNT,
  CLEAR_CART,
  COUNT_CART_TOTALS,
};
